### ISSUE TITLE
Error comparing DB_POINTER attributes

### ISSUE THREAD

**Issue by arisnegro** [mongounit/mongounit#31]
Hi!

When the expected value is a DB_POINTER, MongoUnit fails loading the dataset.

Expected data:
`"fieldDbPointer": { "$$DB_POINTER": { "namespace": "categories", "objectId": "5db7545b7b615c739732c773" }}`

Error:
org.bson.BsonInvalidOperationException: Value expected to be of type OBJECT_ID is of unexpected type DB_POINTER

	at org.bson.BsonValue.throwIfInvalidType(BsonValue.java:419)
	at org.bson.BsonValue.asObjectId(BsonValue.java:150)
	at org.mongounit.MongoUnitUtil.getFieldValue(MongoUnitUtil.java:493)
	at org.mongounit.MongoUnitUtil.getDocument(MongoUnitUtil.java:331)

Bye!!

**Comment by ychaikin** [comment]
Will investigate... Can you provide an example of an export of mongoDB dataset that uses DB_POINTER type?
